name: simulation-image amd64

on:
  schedule:
    - cron: '0 3 * * 6'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write

    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet &
          sudo rm -rf /usr/local/lib/android &
          sudo rm -rf /opt/ghc &
          sudo rm -rf /opt/hostedtoolcache/CodeQL &
          sudo rm -rf /usr/local/share/boost &
          sudo rm -rf /usr/share/swift &
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" &
          wait
          sudo docker image prune --all --force
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/* 

      - name: Add swap space
        run: |
          sudo fallocate -l 10G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Check swap
        run: |
          free -h
          sudo swapon --show

      - name: Check disk space
        run: df -h

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Clone external repos
        run: CLONE_ONLY=true ./scripts/sim_build.sh

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the simulation image (optionally, add --push)
        run: docker buildx build -t ghcr.io/jacopopan/simulation-image:latest -f ./scripts/docker/Dockerfile.simulation .
